spring:
  application:
    name: persistence
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8091
  context-path: /graducation
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@peer1:8761/graducation/eureka/,http://root:123456@peer2:8762/graducation/eureka/,http://root:123456@peer3:8763/graducation/eureka/
  instance:
    prefer-ip-address: true
logging:
  level: debug