server:
  port: 8091
  context-path: /graducation
eureka:
  client:
    service-url:
      defaultZone: ${E_URL1},${E_URL2},${E_URL3}
  instance:
    prefer-ip-address: true
spring:
  application:
    name: persistence
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level: debug
db:
  ##从库数量
  datasource_num: 2
  ##单个从库中从表数量
  table_num: 2
  ##主表名List
  table_names: user
  ##主库名，从库名为主库名+0~datasource_num
  data_name: db
  ##分表键
  table_key: username
  ##分表策略截取id长度，分库从0-key_length,分表从key_length-end
  key_length: 4
  ##主库
  main_data: dbo
  ##默认库,当没有配置策略时使用
  default_data: db0
  dbconfig:
    datasource1:
      ##定义名字时必须末尾从0开始的连续数字
      data_name: db0
      driver_class: com.mysql.jdbc.Driver
      url: jdbc:mysql:///db0?useUnicode=true&characterEncoding=utf-8&useSSL=true
      user_name: root
      password: 123456
    datasource2:
      data_name: test1
      driver_class: com.mysql.jdbc.Driver
      url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf-8&useSSL=true
      user_name: root
      password: 123456