server:
  port: 8079
  context-path: /graducation
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@peer1:8761/graducation/eureka/,http://root:123456@peer2:8762/graducation/eureka/,http://root:123456@peer3:8763/graducation/eureka/
  instance:
    prefer-ip-address: true
#    home-page-url-path: /
spring:
  application:
    name: hystrix-turbine
turbine:
  instanceUrlSuffix: graducation/hystrix.stream
  aggregator:
    clusterConfig: default
  appConfig: backstage
  cluster-name-expression: "'default'"